; My php.ini settings
; Fix for PCRE "JIT compilation failed" error
[Pcre]
;pcre.jit=0
;max_execution_time = 250
;max_input_time = 250
output_buffering = On
;post_max_size = 750M
;upload_max_filesize = 750M
;memory_limit = 450M
;xdebug.remote_enable=1 - onlyfor xdebug 2.*
;xdebug.remote_handler=dbgp
;xdebug.remote_autostart=1
;xdebug.remote_connect_back=1
